package com.example.barbershop.entity;

public enum AppointmentHistoryAction {
    CREATED,
    RESCHEDULED,
    CANCELLED,
    STATUS_CHANGED,
    CONFIRMATION_CREATED,
    CONFIRMED,
    REJECTED,
    EXPIRED,
    CUSTOMER_CLAIMED,
    CUSTOMER_ARRIVED,
    APPOINTMENT_COMPLETED,
    CUSTOMER_NO_SHOW,
    BARBER_CANCELLED
}
