spring.application.name=barber-shop
appointment.no-show-grace-minutes=15
appointment.customer-change-cutoff-minutes=120
auth.otp.resend-cooldown-seconds=60
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
barbershop.api.version=@project.version@
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.display-request-duration=true
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
